# Generated by Django 4.2.21 on 2025-05-24 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='YouTubeVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(max_length=255, unique=True)),
                ('extracted_date', models.CharField(max_length=255)),
                ('upload_date', models.CharField(max_length=255)),
                ('channel_name', models.CharField(max_length=255)),
                ('subscriber_count', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('view_count', models.CharField(max_length=255)),
                ('video_url', models.URLField(unique=True)),
                ('product_count', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='YouTubeProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(blank=True, max_length=500)),
                ('product_price', models.CharField(blank=True, max_length=100)),
                ('product_image_link', models.URLField(blank=True, max_length=1000)),
                ('product_merchant', models.CharField(blank=True, max_length=100)),
                ('product_merchant_link', models.URLField(blank=True, max_length=1000)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='youtube_crawling.youtubevideo')),
            ],
        ),
    ]
