# Generated by Django 4.2.21 on 2025-05-24 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_crawling', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='youtubeproduct',
            unique_together={('video', 'product_name')},
        ),
    ]
