# Generated by Django 4.2.21 on 2025-05-24 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_crawling', '0002_alter_youtubeproduct_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtubevideo',
            name='product_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
