# Generated by Django 4.2.21 on 2025-05-26 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_crawling', '0003_alter_youtubevideo_product_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtubeproduct',
            name='product_image_link',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='youtubeproduct',
            name='product_merchant_link',
            field=models.TextField(blank=True),
        ),
    ]
