# Generated by Django 4.2.21 on 2025-05-26 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_crawling', '0004_alter_youtubeproduct_product_image_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtubeproduct',
            name='product_image_link',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='youtubeproduct',
            name='product_merchant',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='youtubeproduct',
            name='product_merchant_link',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='youtubeproduct',
            name='product_name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='youtubeproduct',
            name='product_price',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='youtubevideo',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='youtubevideo',
            name='extracted_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='youtubevideo',
            name='product_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='youtubevideo',
            name='subscriber_count',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='youtubevideo',
            name='title',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='youtubevideo',
            name='upload_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='youtubevideo',
            name='video_url',
            field=models.URLField(max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='youtubevideo',
            name='view_count',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='youtubeproduct',
            index=models.Index(fields=['product_price'], name='youtube_cra_product_a2e43f_idx'),
        ),
        migrations.AddIndex(
            model_name='youtubeproduct',
            index=models.Index(fields=['product_merchant'], name='youtube_cra_product_3ff2e8_idx'),
        ),
        migrations.AddIndex(
            model_name='youtubevideo',
            index=models.Index(fields=['extracted_date'], name='youtube_cra_extract_a6f733_idx'),
        ),
        migrations.AddIndex(
            model_name='youtubevideo',
            index=models.Index(fields=['upload_date'], name='youtube_cra_upload__d8854d_idx'),
        ),
        migrations.AddIndex(
            model_name='youtubevideo',
            index=models.Index(fields=['channel_name'], name='youtube_cra_channel_2c6a12_idx'),
        ),
    ]
