# Generated by Django 5.2.1 on 2025-05-15 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shorts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stack_date', models.DateField()),
                ('created_date', models.DateField(auto_now_add=True)),
                ('channel_name', models.CharField(max_length=200)),
                ('video_title', models.CharField(max_length=200)),
                ('video_url', models.URLField()),
                ('video_thumbnail', models.URLField()),
                ('upload_date', models.DateTimeField()),
                ('video_views', models.IntegerField()),
                ('subscriber_count', models.IntegerField()),
            ],
        ),
    ]
