# Generated by Django 5.2.1 on 2025-05-15 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crawl', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shorts',
            name='video_thumbnail',
        ),
    ]
