# Generated by Django 5.2.1 on 2025-05-21 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawl', '0002_remove_shorts_video_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shorts',
            name='upload_date',
            field=models.DateField(),
        ),
    ]
